// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApd8xDolnbJ9QvWc37GRErHoVwWkP8V7U',
    appId: '1:918557545932:web:0afce32cc56d26d86af969',
    messagingSenderId: '918557545932',
    projectId: 'data-d2b6d',
    authDomain: 'data-d2b6d.firebaseapp.com',
    storageBucket: 'data-d2b6d.appspot.com',
    measurementId: 'G-M6DMYWR4J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfME9hUPv9RmGD8rnNwqYMnzqmFMsb8E0',
    appId: '1:918557545932:android:b2a859e715c549ff6af969',
    messagingSenderId: '918557545932',
    projectId: 'data-d2b6d',
    storageBucket: 'data-d2b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Atm93p7jE3sUZCh1ZKIpjVbPfKF9dsk',
    appId: '1:918557545932:ios:01d6882ca5fc1aa56af969',
    messagingSenderId: '918557545932',
    projectId: 'data-d2b6d',
    storageBucket: 'data-d2b6d.appspot.com',
    androidClientId: '918557545932-11l6m3d3etdd6q34jbjps5e7ouqtl7d8.apps.googleusercontent.com',
    iosClientId: '918557545932-7kq8v0jiji3nhlpat2k0gvvho4v2btdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalDalali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Atm93p7jE3sUZCh1ZKIpjVbPfKF9dsk',
    appId: '1:918557545932:ios:9ed16aee61f845286af969',
    messagingSenderId: '918557545932',
    projectId: 'data-d2b6d',
    storageBucket: 'data-d2b6d.appspot.com',
    androidClientId: '918557545932-11l6m3d3etdd6q34jbjps5e7ouqtl7d8.apps.googleusercontent.com',
    iosClientId: '918557545932-r1psodnl66qkodum66mk3252cv8r39v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalDalali.RunnerTests',
  );
}
